### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-localstorage-wMUDce#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-js-localstorage-wmudce-kisyular.surge.sh/) and meets the following criteria:

- [x] Includes a button that when clicked, will toggle the website between day and night themes
- [x] When a user changes the theme, their choice is remembered in `localStorage`
- [x] The class on the `body` element is always up-to-date with the current theme (either `day-theme` or `night-theme`) -- you can use `document.body.setAttribute('class', 'some-class-name')` to set the class on the `body`
- [x] When the body has the class `day-theme`, the background of the website is light-colored, with a darker color for the text
- [x] When the body has the class `night-theme`, the background of the website is a very dark color, with a lighter color for the text
- [x] Somewhere on the page, the user is told how many times they've visited the website (starting with `1` the first time)

**Comment by stuartpearman** [comment]
Hey Rellika, this looks awesome! I appreciate the extra effort you put into this. There are 2 things that could be even better:

Instead of using the `onclick` attributes to call your functions, use javascript event listeners. [This slide](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/js-intro/6) from the lesson talks about event listeners.

And I also saw some inconsistent indentation in your index.html file.

Nice work Rellika, let me know when you've made changes!

**Comment by kisyular** [comment]
Hi @stuartpearman, I made the changes you suggested. Kindly take a look

**Comment by stuartpearman** [comment]
Nice! Awesome job Rellika, this is sweet 😎 :shipit:
